"""baseline: o schema que existia antes do runner de migrations.

Revision ID: 0001
Revises:
Create Date: 2026-08-17

Gerada por autogenerate contra um PostgreSQL vazio (ADR-0029): descreve exatamente o que
`Base.metadata.create_all` mais os cinco blocos de `ALTER TABLE … ADD COLUMN` e os dois
`CREATE UNIQUE INDEX` do antigo `Database.create_schema()` produziam juntos. Banco que já
existia antes do runner é CARIMBADO nesta revisão por `croquito_api.bootstrap`, depois de
conferir que as colunas mais recentes estão presentes — nada é recriado.

As tabelas da medição (`valuation_rounds`, `valuation_round_revisions`, ADR-0028) NÃO
estão aqui de propósito: elas pertencem a F-003, que é o primeiro uso deste mecanismo.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "operation", "key", name="uq_idempotency_scope"),
    )
    op.create_index(
        op.f("ix_idempotency_records_tenant_id"), "idempotency_records", ["tenant_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("default_unit", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_tenant_id"), "projects", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_ai_processing_entitlements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("agreement_reference", sa.String(length=128), nullable=False),
        sa.Column("authorized_by", sa.String(length=128), nullable=False),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_ai_entitlement_tenant"),
    )
    op.create_index(
        op.f("ix_tenant_ai_processing_entitlements_tenant_id"),
        "tenant_ai_processing_entitlements",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(op.f("ix_uploads_tenant_id"), "uploads", ["tenant_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("upload_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("upload_id"),
    )
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    op.create_table(
        "ai_processing_consents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("accepted_by", sa.String(length=128), nullable=False),
        sa.Column("notice_version", sa.String(length=32), nullable=False),
        sa.Column("providers_json", sa.JSON(), nullable=False),
        sa.Column("global_processing", sa.Boolean(), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("authorization_source", sa.String(length=32), nullable=True),
        sa.Column("entitlement_id", sa.String(length=36), nullable=True),
        sa.Column("agreement_reference", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entitlement_id"],
            ["tenant_ai_processing_entitlements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_processing_consents_job_id"), "ai_processing_consents", ["job_id"], unique=True
    )
    op.create_index(
        op.f("ix_ai_processing_consents_tenant_id"),
        "ai_processing_consents",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "scene_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.String(length=36), nullable=True),
        sa.Column("scene", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "version", name="uq_scene_version"),
    )
    op.create_index(op.f("ix_scene_revisions_job_id"), "scene_revisions", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_scene_revisions_tenant_id"), "scene_revisions", ["tenant_id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("source_revision_id", sa.String(length=36), nullable=False),
        sa.Column("approved_revision_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column("reviewer_roles", sa.JSON(), nullable=False),
        sa.Column("acknowledgement", sa.Text(), nullable=False),
        sa.Column("approval_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_revision_id"],
            ["scene_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_revision_id"],
            ["scene_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_job_id"), "approvals", ["job_id"], unique=False)
    op.create_index(op.f("ix_approvals_tenant_id"), "approvals", ["tenant_id"], unique=False)
    op.create_table(
        "review_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_review_id", sa.String(length=36), nullable=True),
        sa.Column("packet_json", sa.JSON(), nullable=False),
        sa.Column("associations_json", sa.JSON(), nullable=False),
        sa.Column("proposals_json", sa.JSON(), nullable=True),
        sa.Column("selected_associations_json", sa.JSON(), nullable=False),
        sa.Column("calibration_json", sa.JSON(), nullable=True),
        sa.Column("proposal_decisions_json", sa.JSON(), nullable=True),
        sa.Column("trace_acceptance_json", sa.JSON(), nullable=True),
        sa.Column("evidence_refs_json", sa.JSON(), nullable=False),
        sa.Column("solver_request_json", sa.JSON(), nullable=True),
        sa.Column("solver_blockers_json", sa.JSON(), nullable=False),
        sa.Column("required_blocker_codes_json", sa.JSON(), nullable=False),
        sa.Column("required_criteria_texts_json", sa.JSON(), nullable=True),
        sa.Column("scene_revision_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_revision_id"],
            ["scene_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "version", name="uq_review_version"),
    )
    op.create_index(
        op.f("ix_review_revisions_job_id"), "review_revisions", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_revisions_tenant_id"), "review_revisions", ["tenant_id"], unique=False
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("base_review_revision_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_review_revision_id"],
            ["review_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_job_id"), "chat_sessions", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_chat_sessions_tenant_id"), "chat_sessions", ["tenant_id"], unique=False
    )
    op.create_table(
        "export_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("scene_revision_id", sa.String(length=36), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("package_object_key", sa.String(length=512), nullable=True),
        sa.Column("dxf_sha256", sa.String(length=64), nullable=True),
        sa.Column("audit_status", sa.String(length=16), nullable=True),
        sa.Column("audit_json", sa.JSON(), nullable=True),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_revision_id"],
            ["scene_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "scene_revision_id", "format", name="uq_export_target"),
    )
    op.create_index(
        op.f("ix_export_artifacts_job_id"), "export_artifacts", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_export_artifacts_tenant_id"), "export_artifacts", ["tenant_id"], unique=False
    )
    op.create_table(
        "proposal_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("review_revision_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column("reviewer_role", sa.String(length=32), nullable=False),
        sa.Column("scene_revision_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_revision_id"],
            ["review_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_revision_id"],
            ["scene_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proposal_decisions_job_id"), "proposal_decisions", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_proposal_decisions_tenant_id"), "proposal_decisions", ["tenant_id"], unique=False
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("review_revision_id", sa.String(length=36), nullable=False),
        sa.Column("reading_id", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column("reviewer_role", sa.String(length=32), nullable=False),
        sa.Column("association_proposal_id", sa.String(length=32), nullable=True),
        sa.Column("decision_id", sa.String(length=32), nullable=True),
        sa.Column("rectifies_decision_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_revision_id"],
            ["review_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_revision_id", "reading_id", name="uq_review_decision_reading"),
    )
    op.create_index(
        op.f("ix_review_decisions_job_id"), "review_decisions", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_decisions_tenant_id"), "review_decisions", ["tenant_id"], unique=False
    )
    op.create_table(
        "trace_solves",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("base_review_revision_id", sa.String(length=36), nullable=False),
        sa.Column("base_scene_revision_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("acceptance_id", sa.String(length=32), nullable=False),
        sa.Column("acceptance_json", sa.JSON(), nullable=False),
        sa.Column("associations_json", sa.JSON(), nullable=False),
        sa.Column("note_associations_json", sa.JSON(), nullable=False),
        sa.Column("derived_dimensions_json", sa.JSON(), nullable=False),
        sa.Column("dimension_texts_json", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=True),
        sa.Column("feature_id", sa.String(length=64), nullable=False),
        sa.Column("solve_status", sa.String(length=24), nullable=True),
        sa.Column("blockers_json", sa.JSON(), nullable=False),
        sa.Column("unapplied_reading_ids_json", sa.JSON(), nullable=False),
        sa.Column("residual_summary_json", sa.JSON(), nullable=True),
        sa.Column("exact_entity_count", sa.Integer(), nullable=True),
        sa.Column("approximate_entity_count", sa.Integer(), nullable=True),
        sa.Column("note_count", sa.Integer(), nullable=True),
        sa.Column("scale_m_per_px", sa.Float(), nullable=True),
        sa.Column("detail_group_scales_json", sa.JSON(), nullable=False),
        sa.Column("result_scene_revision_id", sa.String(length=36), nullable=True),
        sa.Column("result_review_revision_id", sa.String(length=36), nullable=True),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_review_revision_id"],
            ["review_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["base_scene_revision_id"],
            ["scene_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_review_revision_id"],
            ["review_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_scene_revision_id"],
            ["scene_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trace_solves_job_id"), "trace_solves", ["job_id"], unique=False)
    op.create_index(op.f("ix_trace_solves_tenant_id"), "trace_solves", ["tenant_id"], unique=False)
    op.create_table(
        "chat_turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("anchor_refs_json", sa.JSON(), nullable=False),
        sa.Column("answer_json", sa.JSON(), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("model_id", sa.String(length=160), nullable=True),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column("input_digest", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.String(length=24), nullable=True),
        sa.Column("raw_response_ref", sa.String(length=512), nullable=True),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_chat_turn_sequence"),
    )
    op.create_index(op.f("ix_chat_turns_job_id"), "chat_turns", ["job_id"], unique=False)
    op.create_index(op.f("ix_chat_turns_session_id"), "chat_turns", ["session_id"], unique=False)
    op.create_index(op.f("ix_chat_turns_tenant_id"), "chat_turns", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Forward-only por decisão (ADR-0029, D2): reverter é apontar a revisão anterior da
    # imagem, não desfazer DDL num banco hospedado.
    raise NotImplementedError(
        "Migrations são forward-only (ADR-0029): reverta apontando a revisão anterior da imagem."
    )
